# Generated by Django 3.1.7 on 2021-04-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('post', models.TextField(max_length=1000)),
                ('dat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
