# Generated by Django 3.1.7 on 2021-04-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(choices=[('harshal', 'harshal'), ('Inder', 'Inder'), ('akshay', 'akshay'), ('Inder', 'Inder')], max_length=50)),
            ],
        ),
    ]
