# Generated by Django 3.1.7 on 2021-04-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ch',
        ),
        migrations.AddField(
            model_name='blog',
            name='upd',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='blog',
            name='post',
            field=models.TextField(max_length=100000000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
