# Generated by Django 3.1.7 on 2021-04-05 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ch',
        ),
    ]
